/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard/vehicles'
import { Route as DashboardTripsRouteImport } from './routes/dashboard/trips'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardMaintenanceRouteImport } from './routes/dashboard/maintenance'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard/expenses'
import { Route as DashboardDriversRouteImport } from './routes/dashboard/drivers'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTripsRoute = DashboardTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMaintenanceRoute = DashboardMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDriversRoute = DashboardDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/drivers': typeof DashboardDriversRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/drivers': typeof DashboardDriversRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/drivers': typeof DashboardDriversRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/drivers'
    | '/dashboard/expenses'
    | '/dashboard/maintenance'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/trips'
    | '/dashboard/vehicles'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/drivers'
    | '/dashboard/expenses'
    | '/dashboard/maintenance'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/trips'
    | '/dashboard/vehicles'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/drivers'
    | '/dashboard/expenses'
    | '/dashboard/maintenance'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/trips'
    | '/dashboard/vehicles'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/trips': {
      id: '/dashboard/trips'
      path: '/trips'
      fullPath: '/dashboard/trips'
      preLoaderRoute: typeof DashboardTripsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/maintenance': {
      id: '/dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/dashboard/maintenance'
      preLoaderRoute: typeof DashboardMaintenanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/drivers': {
      id: '/dashboard/drivers'
      path: '/drivers'
      fullPath: '/dashboard/drivers'
      preLoaderRoute: typeof DashboardDriversRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDriversRoute: typeof DashboardDriversRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardMaintenanceRoute: typeof DashboardMaintenanceRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTripsRoute: typeof DashboardTripsRoute
  DashboardVehiclesRoute: typeof DashboardVehiclesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDriversRoute: DashboardDriversRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardMaintenanceRoute: DashboardMaintenanceRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTripsRoute: DashboardTripsRoute,
  DashboardVehiclesRoute: DashboardVehiclesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
